In [8]:
import numpy as np
import pandas as pn
import sys
sys.path.append("../")
from logisticMethods import LogisticRegressionMethods as METHODS
#setosa ->0
# versicolor->1
#virginica ->2
values = [
    'setosa','versicolor','virginica'
]
MT = METHODS()


In [9]:
fullDataset = MT.removeBlanks(pn.read_csv("./Iris/iris.csv").values)
[X,Y] = MT.returnXY(fullDataset)
print(X.shape)
print(Y.shape)
[X,means,stds] = MT.scaleDown(X)
print(stds)

(150, 4)
(150, 1)
[0.82530129 0.43214658 1.75852918 0.76061262]


In [10]:
print(means)
X = MT.addOne(X)
[trainingDataset,testingDataset] = MT.splitDataset(X)
[trainingResults,testingResults] = MT.splitDataset(Y)

[5.84333333 3.054      3.75866667 1.19866667]


In [11]:
def oneVSAll(Y,number):
    return Y==number

In [12]:
def getMax(arr1,arr2,arr3,length):
    print(length)
    finalResult = np.ones([length,1])
    
    for i in range(length):
        tempDict = {str(arr1[i]) : 0,str(arr2[i]) : 1,str(arr3[i]) : 2}
        tempResult = max(arr1[i],arr2[i],arr3[i])
        finalResult[i] = tempDict[str(tempResult)]
    return finalResult

In [13]:
iterations = 20000
alpha = 0.3
length = X.shape[1]


tempY0 = oneVSAll(trainingResults,0)
theta0 = MT.gradientDescent(trainingDataset,tempY0,np.ones([length,1]),alpha,iterations)
# theta0 = np.array([[-4.41151074]
#  [-1.8981038 ]
#  [ 2.96538444]
#  [-4.14109387]
#  [-3.77202671]])
print(theta0)


theta1 = np.ones([length,1])
tempY1 = oneVSAll(trainingResults,1)
theta1 = MT.gradientDescent(trainingDataset,tempY1,theta1,alpha,iterations)
# theta1 = np.array([[-0.47353269]
#  [-0.51104327]
#  [-1.13774076]
#  [ 3.48600275]
#  [-2.48781406]])


theta2 = np.ones([length,1])
tempY2 = oneVSAll(trainingResults,2)
theta2 = MT.gradientDescent(trainingDataset,tempY2,theta2,alpha,iterations)
# theta2 = np.array([[-10.33232867]
#  [ -0.39743409]
#  [ -0.79501535]
#  [  9.06281166]
#  [  6.05402489]])


[[-5.15328358]
 [-2.06975661]
 [ 3.29092737]
 [-4.83942775]
 [-4.42517497]]


In [14]:
totalTestCases = len(testingResults)
result0 = (MT.sigmoid(np.matmul(trainingDataset,theta0)))
result1 = (MT.sigmoid(np.matmul(trainingDataset,theta1)))
result2 = (MT.sigmoid(np.matmul(trainingDataset,theta2)))
finalResult = getMax(result0,result1,result2,totalTestCases)
print(f"Running {totalTestCases} tests...")
right = 0
for i in range(totalTestCases):
    if (finalResult[i] == testingResults[i]):
        right+=1
print(right)
    
    


45
Running 45 tests...
12
